# **Import libraries, module and function**

In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# **Create a Tensor**

In [19]:
# Create a tensor
x = torch.tensor([1.0,2.0,3.0])

zeros = torch.zeros(3,3)
ones = torch.ones(3,3)

rand = torch.rand(3,3)

print(x)
print(zeros)
print(ones)
print(rand)

tensor([1., 2., 3.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0918, 0.1854, 0.6542],
        [0.9509, 0.1056, 0.2328],
        [0.4837, 0.3827, 0.8173]])


This code snippet demonstrates different ways to create tensors in PyTorch. A tensor is created from a Python list, alongside tensors filled with zeros and ones, and a tensor containing randomly generated values. The output displays the resulting tensor structures and values, illustrating common methods used to initialize tensors for deep learning workflows.

## Basic aritmetic





Tensor arithmetic works element-wise, meaning PyTorch applies the operation across every value in the tensor simultaneously rather than looping through one by one. This is what makes tensors so fast – and it is also what makes GPU acceleration so powerful, since GPUs are specifically designed to run thousands of these operations in parallel.

In [20]:
a = torch.tensor([1.0, 2.0, 3.0, 4.0])
b = torch.tensor([5.0, 6.0, 7.0, 8.0])

print(a + b)
print(a * b)
print(b.sum())
print(a.mean())

tensor([ 6.,  8., 10., 12.])
tensor([ 5., 12., 21., 32.])
tensor(26.)
tensor(2.5000)


This code snippet demonstrates common mathematical operations on PyTorch tensors. Two tensors are added and multiplied element-wise, while functions such as sum() and mean() are used to compute the total and average values of the tensor elements. The output displays the results of these operations, highlighting how PyTorch efficiently performs numerical computations on tensor data.

## **Reshaped**

In deep learning, you will constantly need to reshape tensors – for example, flattening a 2D image into a 1D vector before passing it into a fully connected layer or reorganizing a batch of data to match what a model expects as input. PyTorch makes this straightforward with reshape(), which rearranges the data into a new shape without changing the underlying values.

In [21]:
x = torch.ones(6) #[1,1,1,1,1,1]
x_reshaped = x.reshape(2,3)
print(x_reshaped)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


This code snippet demonstrates how to change the shape of a tensor using the reshape() function. A one-dimensional tensor of ones containing six elements is reshaped into a 2×3 tensor. The output shows the updated tensor structure, confirming that the data has been reorganized without altering its values.

##**Moving to GPU**

By default, tensors are created on the CPU, but moving them to a GPU – where matrix operations can run orders of magnitude faster – takes just one line. This allows the same code to run on both GPU-equipped machines and machines that only have a CPU.  It is good practice to check whether a GPU is available.




In [22]:
if torch.cuda.is_available():
  x = x.to("cuda")

In [23]:
x

tensor([1., 1., 1., 1., 1., 1.], device='cuda:0')

This code checks whether a CUDA-enabled GPU is available using torch.cuda.is_available(). If a GPU is available, the tensor x is moved from the CPU to the GPU using .to("cuda"). This enables faster computation by leveraging GPU acceleration, which is especially useful for large-scale deep learning tasks.

## **Converting to and from NumPy**

PyTorch and NumPy use nearly the same language, so switching between them is simple. Chances are you are already using NumPy somewhere in your pipeline – for loading data, preprocessing, or visualizing results.

 You can convert between tensors and NumPy arrays in one line, and on the CPU, they even share the same memory, so there is no performance cost to switching between them.

In [24]:
import numpy as np
import torch

tensor = torch.tensor([1.0,2.0,3.0])
numpy_array = tensor.numpy()

# Tensor to Numpy
print(f'Originial pytorch Tensor: ,{tensor}')

print(f'Converted to Numpy array: , {numpy_array}')


#numpy to tensor
numpy_array2 = np.array([1.0,2.0,3.0])
tensor2 = torch.from_numpy(numpy_array2)

print(f'Originial Numpy array: ,{numpy_array2}')

print(f'Converted to pytorch Tensor: , {tensor2}')

Originial pytorch Tensor: ,tensor([1., 2., 3.])
Converted to Numpy array: , [1. 2. 3.]
Originial Numpy array: ,[1. 2. 3.]
Converted to pytorch Tensor: , tensor([1., 2., 3.], dtype=torch.float64)


This snippet demonstrates interoperability between PyTorch and NumPy. A PyTorch tensor is first converted into a NumPy array using .numpy(), and then a NumPy array is converted back into a PyTorch tensor using torch.from_numpy(). The output shows that the values remain unchanged during the conversion process, highlighting seamless data sharing between the two libraries. This is particularly useful when integrating PyTorch models with NumPy-based preprocessing or analysis workflows.

In [25]:
import numpy as np
import torch

# Tensor Initialization

#### Directly from data

Tensors can be created directly from data. The data type is automatically inferred.

In [26]:
data = [[1,2],[3,4]]
df = torch.tensor(data)

In [27]:
data

[[1, 2], [3, 4]]

In [28]:
df

tensor([[1, 2],
        [3, 4]])

#### From a NumPy array

Tensors can be created from NumPy arrays

In [29]:
np_array = np.array([[[1,2],[3,4],[5,6]]])
df  = torch.tensor(np_array)

In [30]:
np_array

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [31]:
df

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

#### From another tensor:

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [32]:
x_ones = torch.ones_like(df) # retain the data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(df, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[[1, 1],
         [1, 1],
         [1, 1]]]) 

Random Tensor: 
 tensor([[[0.4275, 0.8457],
         [0.9232, 0.6207],
         [0.7457, 0.1101]]]) 



#### With random or constant values:

shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [33]:
shape = (2,3)
rand_tens = torch.rand(shape)
ones_tens = torch.ones(shape)
zero_tens = torch.zeros(shape)
print(rand_tens)
print(ones_tens)
print(zero_tens)

tensor([[0.5950, 0.5827, 0.8506],
        [0.7564, 0.7219, 0.4127]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Tensor Attributes

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [34]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Tensor Operations

Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described [here](https://docs.pytorch.org/docs/2.13/torch.html).

Each of them can be run on the GPU (at typically higher speeds than on a CPU). If you're using Colab, allocate a GPU by going to Edit > Notebook Settings.

In [35]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available()  else "cpu"

tensor = torch.randn(3, 3) # Create a sample tensor
tensor = tensor.to(device)
print(f"Device tensor is stored on:{tensor.device}")

Device tensor is stored on:cuda:0


#### Standard numpy-like indexing and slicing:

In [36]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Standard numpy-like indexing and slicing:

In [37]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 0., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Joinnig tensors

You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also [torch.stack](https://docs.pytorch.org/docs/2.13/generated/torch.stack.html), another tensor joining op that is subtly different from torch.cat.

In [38]:
x = torch.rand(2,3)

torch.cat((x,x),0)
torch.cat((x,x,x),1)

tensor([[0.2365, 0.1163, 0.8365, 0.2365, 0.1163, 0.8365, 0.2365, 0.1163, 0.8365],
        [0.6487, 0.5327, 0.7447, 0.6487, 0.5327, 0.7447, 0.6487, 0.5327, 0.7447]])

#### Multiplying tensors

In [39]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

#This computes the matrix multiplication between two tensors

print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


#### In-place operations

Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x.

In [40]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>

</div>



Tensor to NumPy array
======================

In [41]:
t = torch.ones(6)
n = t.numpy()

In [42]:
t,n

(tensor([1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1.], dtype=float32))

A change in the tensor reflects in the NumPy array.


In [43]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2. 2.]


NumPy array to Tensor
=====================


In [44]:
n = np.ones(5)
t = torch.from_numpy(n)

In [45]:
n,t

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

Changes in the NumPy array reflects in the tensor.


In [46]:
np.add(n,3, out = n)
print(f"t: {t}")
print(f"n:{n}")

t: tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
n:[4. 4. 4. 4. 4.]
