# History

PyTorch traces its roots to Torch, a scientific computing framework that used Lua; in 2016, researchers at Facebook’s AI Research Lab (FAIR), now Meta AI, reinvented it for Python, creating PyTorch, which is today a Linux Foundation community project.


By 2024, PyTorch had established itself as the most popular deep learning framework, with a 63% adoption rate in the model training space, used in over 70% of AI research implementations. In 2025, the PyTorch Foundation’s ecosystem grew to include large-scale projects such as vLLM, DeepSpeed, and Ray, all of which are governed independently.

The annual PyTorch Conference attracted more than 3,400 attendees and gained 16 new industry members, including Snowflake, Dell Technologies, and Qualcomm. Also, it is trusted in production by organizations such as Meta, Microsoft, OpenAI, and Tesla. For developers and data scientists looking to enter deep learning, PyTorch remains the most practical and widely supported starting point available today.

PyTorch was built on two foundations:


> GPU-accelerated tensor computation as a more powerful alternative to NumPy


> automatic differentiation engine for training neural networks





# INFO



*   A replacement for NumPy to use the power of GPUs and other accelerators.


*   An automatic differentiation library that is useful to implement neural networks.
*   PyTorch traces its roots to Torch


---

PyTorch is an open-source deep learning framework designed to simplify the process of building neural networks and machine learning models






## Core Features of pytorch framework

`Dynamic computation graphs (define-by-run):` As code executes, PyTorch builds computation graphs. These are maps of every mathematical operation your model performs: things like multiplying inputs by weights, adding biases, and applying activation functions. PyTorch needs to track these because training requires working backwards through all of those steps to calculate how much each weight contributed to the model’s error, so it knows how to adjust them to improve. Computation graphs allow the model structure to be modified during runtime and facilitate debugging using standard Python tools, making PyTorch ideal for research and experimentation.

`Pythonic and intuitive interface`: PyTorch code is Pythonic, which reduces the learning curve. It uses standard Python control flow and clean, readable syntax, and it integrates well with Pythonic libraries.
Strong GPU acceleration: PyTorch has seamless support for GPUs using CUDA. There is easy device switching and efficient tensor computations on GPUs. It also supports multi-GPU training.

`Autograd (automatic differentiation)`: There is a built-in autograd engine that automatically computes gradients. It tracks operations on tensors and enables backpropagation with minimal code.


`Rich neural network library`: PyTorch provides a comprehensive module for building models. There are prebuilt layers, loss functions, activation functions, and a modular design for custom architectures.

`Extensive ecosystem`: PyTorch is not just a framework – it is an ecosystem. There is a wide array of tools, even beyond the AI-specific libraries. Hence, an entire AI project can be managed under the Python umbrella from data collection to deployment.

`Model deployment support`: PyTorch supports deploying models from research to production, with support for both mobile and edge deployments. What’s more, it also has TorchScript for optimized execution and ONNX export for interoperability.

`Broad community and industry adoption`: PyTorch is backed by Meta, and it has a large and active community. Due to Python being one of the largest programming communities worldwide, PyTorch users benefit from shared knowledge, resources, and tools. There is extensive documentation and tutorials, and it is widely used in academia and industry.

## Understanding PyTorch tensors
* tensors arwe the core data structures in pytorch
*
hey are like n-dimensional arrays and matrices, but unlike regular arrays, tensors can be used on hardware accelerators like GPUs

*Think of tensors as an extension of numbers we are already familiar with

>A single number is a zero-dimensional tensor,

> a list of numbers is a one-dimensional tensor

> a table of numbers is a two-dimensional tensor

> ou can add more dimensions to represent complex data like images, videos, or audio

Neural networks accept tensors as input and generate tensors as output – even the parameters of a neural network, its weights and biases, are stored as tensors. For a visual explanation:-

Tensors are similar to NumPy arrays but can also run on GPUs or other hardware accelerators. Often, tensors and NumPy arrays can share the same underlying memory, meaning that data doesn’t need to be copied.

The main difference is what happens when the calculation gets serious. NumPy is for scientific computing on a CPU. PyTorch tensors can be moved and processed on GPUs in one line of code, allowing for massive parallel computation and providing significant speedups for the types of matrix multiplication common in deep learning.

This enables the kind of processing that makes training large neural networks possible


# **Import libraries, module and function**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# **Create a Tensor**

In [ ]:
# Create a tensor
x = torch.tensor([1.0,2.0,3.0])

zeros = torch.zeros(3,3)
ones = torch.ones(3,3)

rand = torch.rand(3,3)

print(x)
print(zeros)
print(ones)
print(rand)

tensor([1., 2., 3.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7718, 0.9161, 0.4467],
        [0.7165, 0.2962, 0.8429],
        [0.6460, 0.3334, 0.5286]])


This code snippet demonstrates different ways to create tensors in PyTorch. A tensor is created from a Python list, alongside tensors filled with zeros and ones, and a tensor containing randomly generated values. The output displays the resulting tensor structures and values, illustrating common methods used to initialize tensors for deep learning workflows.

## Basic aritmetic





Tensor arithmetic works element-wise, meaning PyTorch applies the operation across every value in the tensor simultaneously rather than looping through one by one. This is what makes tensors so fast – and it is also what makes GPU acceleration so powerful, since GPUs are specifically designed to run thousands of these operations in parallel.

In [ ]:
a = torch.tensor([1.0, 2.0, 3.0, 4.0])
b = torch.tensor([5.0, 6.0, 7.0, 8.0])

print(a + b)
print(a * b)
print(b.sum())
print(a.mean())

tensor([ 6.,  8., 10., 12.])
tensor([ 5., 12., 21., 32.])
tensor(26.)
tensor(2.5000)


This code snippet demonstrates common mathematical operations on PyTorch tensors. Two tensors are added and multiplied element-wise, while functions such as sum() and mean() are used to compute the total and average values of the tensor elements. The output displays the results of these operations, highlighting how PyTorch efficiently performs numerical computations on tensor data.

## **Reshaped**

In deep learning, you will constantly need to reshape tensors – for example, flattening a 2D image into a 1D vector before passing it into a fully connected layer or reorganizing a batch of data to match what a model expects as input. PyTorch makes this straightforward with reshape(), which rearranges the data into a new shape without changing the underlying values.

In [ ]:
x = torch.ones(6) #[1,1,1,1,1,1]
x_reshaped = x.reshape(2,3)
print(x_reshaped)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


This code snippet demonstrates how to change the shape of a tensor using the reshape() function. A one-dimensional tensor of ones containing six elements is reshaped into a 2×3 tensor. The output shows the updated tensor structure, confirming that the data has been reorganized without altering its values.

##**Moving to GPU**

By default, tensors are created on the CPU, but moving them to a GPU – where matrix operations can run orders of magnitude faster – takes just one line. This allows the same code to run on both GPU-equipped machines and machines that only have a CPU.  It is good practice to check whether a GPU is available.




In [ ]:
if torch.cuda.is_available():
  x = x.to("cuda")

In [ ]:
x

tensor([1., 1., 1., 1., 1., 1.], device='cuda:0')

This code checks whether a CUDA-enabled GPU is available using torch.cuda.is_available(). If a GPU is available, the tensor x is moved from the CPU to the GPU using .to("cuda"). This enables faster computation by leveraging GPU acceleration, which is especially useful for large-scale deep learning tasks.

## **Converting to and from NumPy**

PyTorch and NumPy use nearly the same language, so switching between them is simple. Chances are you are already using NumPy somewhere in your pipeline – for loading data, preprocessing, or visualizing results.

 You can convert between tensors and NumPy arrays in one line, and on the CPU, they even share the same memory, so there is no performance cost to switching between them.

In [ ]:
import numpy as np
import torch

tensor = torch.tensor([1.0,2.0,3.0])
numpy_array = tensor.numpy()

# Tensor to Numpy
print(f'Originial pytorch Tensor: ,{tensor}')

print(f'Converted to Numpy array: , {numpy_array}')


#numpy to tensor
numpy_array2 = np.array([1.0,2.0,3.0])
tensor2 = torch.from_numpy(numpy_array2)

print(f'Originial Numpy array: ,{numpy_array2}')

print(f'Converted to pytorch Tensor: , {tensor2}')

Originial pytorch Tensor: ,tensor([1., 2., 3.])
Converted to Numpy array: , [1. 2. 3.]
Originial Numpy array: ,[1. 2. 3.]
Converted to pytorch Tensor: , tensor([1., 2., 3.], dtype=torch.float64)


This snippet demonstrates interoperability between PyTorch and NumPy. A PyTorch tensor is first converted into a NumPy array using .numpy(), and then a NumPy array is converted back into a PyTorch tensor using torch.from_numpy(). The output shows that the values remain unchanged during the conversion process, highlighting seamless data sharing between the two libraries. This is particularly useful when integrating PyTorch models with NumPy-based preprocessing or analysis workflows.

## **Building neural networks with PyTorch**

In [ ]:
from torchvision import datasets, transforms

## **Loading and normalizing the data**


Before training a neural network, the input data needs to be normalized so that the pixel values are scaled into a consistent range. This helps improve stability by keeping input values centered around zero and ensuring that gradients behave more predictably during optimization

In [ ]:
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))

])

In [ ]:

train_data = datasets.MNIST(
    root = './data',
    train = True,
    download = True,
    transform = transform
    )

100%|██████████| 9.91M/9.91M [00:00<00:00, 19.7MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 473kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.40MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 7.78MB/s]


MNIST images are normalized as part of a preprocessing pipeline using PyTorch transforms:

*  `Transforms.ToTensor()` Converts images from pixel values (0-255) into floating-point tesors scaled to 0-1

*   `Transforms.Normalize((0.5,),(0.5,)) ` then rescales these values to approximately -1 to 1, which helps stabilize training by keeping input values centered around zero and improving gradient behavior during optimization.


PyTorch also provides key data-loading parameters to control how training data is processed:




*   `batch_size=64` means ***the model processes 64 images at a time*** instead of the full dataset. This improves memory efficiency and makes training more stable by allowing gradient updates on mini-groups of data rather than individual samples or the entire dataset.
*  `shuffle=True` randomizes the order of images each epoch, so the model does not memorize the sequence.


* `Download = True` means pytorch fetches MNIST automatically on the first run , so you don't need to download anything manually



## **Defining the model**



After the data is ready the next step is to build the neural network that will learn from it. The goal of the model is to take an input image of a handwritten digit and predict which digit (0–9) it represents

In [ ]:
from torch.nn import functional
from torch import nn

In [ ]:
train_loader = DataLoader(train_data, batch_size=64, shuffle=True)

In [ ]:
class SimpleNetwork(nn.Module):
   def __init__(self):
       super(SimpleNetwork, self).__init__()
       self.fc1 = nn.Linear(784, 128)  # 28x28 = 784 input pixels
       self.fc2 = nn.Linear(128, 64)   # hidden layer
       self.fc3 = nn.Linear(64, 10)    # 10 outputs (digits 0-9)


   def forward(self, x):
       x = x.view(-1, 784)             # flatten the image
       x = F.relu(self.fc1(x))
       x = F.relu(self.fc2(x))
       x = self.fc3(x)
       return x


model = SimpleNetwork()
print(model)

SimpleNetwork(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=10, bias=True)
)


## **Training the model**

## **Choosing a loss function and optimizer**

the model is defined, the next step is to ***train it so it can learn to recognize handwritten digits***. During training, the model processes MNIST images,makes predictions, compares them to correct labels, and gradually improves its performance. To do this, we first need two key components: a loss function and an optimiz

## Loss Function

The loss function measures how far the model’s predictions are from the correct answers. In classification problems like MNIST (which has 10 classes, one for each digit),


---


`CrossEntropyLoss` is used because it is designed for multi-classclassification, and it not only penalizes incorrect predictions but also takes into account how confident the model is when it makes a mistake.




---

The optimizer is responsible for updating the model’s weights based on the loss. It determines how the model learns from its errors.

The difference is how they do it. *SGD updates model weights using a fixed learning rate applied to the computed gradients.* **ADAM extends this idea by adapting the learning rate for each parameter using estimates of past gradients, which often leads to faster and more stable convergence with less manual tuning**. For this project, ADAM is the practical choice, with lr=0.001 as a safe default learning rate. SGD is worth exploring later when you want more control over the training process.

## **Implementing a training loop**

**The training loop is the core of the learning process**. Each full pass through the training data is called an epoch. Training typically runs for multiple epochs so that the model can gradually improve its performance over time.


---


Each epoch is made up of smaller units called batches. Instead of processing the entire dataset at once, the model processes one batch at a time, which makes training more efficient and memory-friendly.

During each epoch, the model processes data in batches and repeats the same steps:


* `Forward pass`: The model makes predictions (logits).
* `Loss computation`: The model compares predictions with true labels.
* `Backward pass`: The model computes gradients of the loss.
* `Weight update:` The optimizer adjusts model parameters.

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("using device", device)

model = SimpleNetwork().to(device)

using device cuda


In [ ]:
# define loss function and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)


#training loop
epochs =5

for epoch in range(epochs):
  model.train()
  running_loss =0

  for images,labels in train_loader:
    #move to GPU/CPU
    images,labels = images.to(device), labels.to(device)
    # forward pass
    prediction = model(images)
    loss = loss_fn(prediction, labels)

    #Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    running_loss += loss.item()

  avg_loss = running_loss / len(train_loader)
  print(f"Epoch {epoch+1}/5 — Loss: {avg_loss:.4f}")

Epoch 1/5 — Loss: 0.3816
Epoch 2/5 — Loss: 0.1852
Epoch 3/5 — Loss: 0.1375
Epoch 4/5 — Loss: 0.1103
Epoch 5/5 — Loss: 0.0949


## **Model Evaluation**

In [ ]:
model.eval()

correct = 0
total = 0

with torch.no_grad(): # no gradient needed
  for images,labels in train_loader:
    images,labels = images.to(device), labels.to(device)

    outputs = model(images)

    #get predicted class
    _, predicted = torch.max(outputs,1)

    total += labels.size(0)
    correct += (predicted == labels).sum().item()

accuracy = 100* correct / total
print(f'test accuracy: {accuracy:.2f}%')


test accuracy: 97.73%


# TENSORS

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters.

Tensors are similar to NumPy's ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing. If you're familiar with ndarrays, you'll be right at home with the Tensor API. If not, follow along in this quick API walkthrough.

In [ ]:
import numpy as np
import torch

# Tensor Initialization

#### Directly from data

Tensors can be created directly from data. The data type is automatically inferred.

In [ ]:
data = [[1,2],[3,4]]
df = torch.tensor(data)

In [ ]:
data

[[1, 2], [3, 4]]

In [ ]:
df

tensor([[1, 2],
        [3, 4]])

#### From a NumPy array

Tensors can be created from NumPy arrays

In [ ]:
np_array = np.array([[[1,2],[3,4],[5,6]]])
df  = torch.tensor(np_array)

In [ ]:
np_array

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
df

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

#### From another tensor:

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [ ]:
x_ones = torch.ones_like(df) # retain the data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(df, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[[1, 1],
         [1, 1],
         [1, 1]]]) 

Random Tensor: 
 tensor([[[0.9750, 0.3721],
         [0.9326, 0.4257],
         [0.8571, 0.4550]]]) 



#### With random or constant values:

shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [ ]:
shape = (2,3)
rand_tens = torch.rand(shape)
ones_tens = torch.ones(shape)
zero_tens = torch.zeros(shape)
print(rand_tens)
print(ones_tens)
print(zero_tens)

tensor([[0.9743, 0.5650, 0.4013],
        [0.8120, 0.4449, 0.7091]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Tensor Attributes

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [ ]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Tensor Operations

Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described [here](https://docs.pytorch.org/docs/2.13/torch.html).

Each of them can be run on the GPU (at typically higher speeds than on a CPU). If you're using Colab, allocate a GPU by going to Edit > Notebook Settings.

In [ ]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available()  else "cpu"

tensor = torch.randn(3, 3) # Create a sample tensor
tensor = tensor.to(device)
print(f"Device tensor is stored on:{tensor.device}")

Device tensor is stored on:cuda:0


#### Standard numpy-like indexing and slicing:

In [ ]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Standard numpy-like indexing and slicing:

In [ ]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([6., 5., 6., 6.])
First column: tensor([6., 6., 6., 6.])
Last column: tensor([6., 6., 6., 6.])
tensor([[6., 0., 6., 6.],
        [6., 0., 6., 6.],
        [6., 0., 6., 6.],
        [6., 0., 6., 6.]])


#### Joinnig tensors

You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also [torch.stack](https://docs.pytorch.org/docs/2.13/generated/torch.stack.html), another tensor joining op that is subtly different from torch.cat.

In [ ]:
x = torch.rand(2,3)

torch.cat((x,x),0)
torch.cat((x,x,x),1)

tensor([[0.8928, 0.7728, 0.1763, 0.8928, 0.7728, 0.1763, 0.8928, 0.7728, 0.1763],
        [0.1860, 0.7918, 0.9733, 0.1860, 0.7918, 0.9733, 0.1860, 0.7918, 0.9733]])

#### Multiplying tensors

In [ ]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

#This computes the matrix multiplication between two tensors

print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


#### In-place operations

Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x.

In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>

</div>



Tensor to NumPy array
======================

In [ ]:
t = torch.ones(6)
n = t.numpy()

In [ ]:
t,n

(tensor([1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1.], dtype=float32))

A change in the tensor reflects in the NumPy array.


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2. 2.]


NumPy array to Tensor
=====================


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
n,t

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

Changes in the NumPy array reflects in the tensor.


In [ ]:
np.add(n,3, out = n)
print(f"t: {t}")
print(f"n:{n}")

t: tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
n:[4. 4. 4. 4. 4.]
